### ISSUE TITLE
你好，代码是不是有的地方有问题呀，有的函数不对呀，preds[ind]这个就不存在呀，eval.py里面的

### ISSUE THREAD

**Issue by Zyt-wenwne** [linhandev/medSeg#7]

**Comment by linhandev** [comment]
你好，这个eval的代码我确实有段时间没用了。但是就你说的这个问题，我看preds是有定义的。eval的脚本要指定yaml的配置文件，在配置文件中写测试分割结果和gt的位置，具体代码在[这](https://github.com/linhandev/medSeg/blob/edd433a8e86218d1759aabec8e5a9a7298b087d2/medseg/eval.py#L54)。
配置文件可以参考config中已有的

**Comment by Zyt-wenwne** [comment]
你好，谢谢，但是你的pred3d.py里面的get_bbs，pad_volume，crop_to_bbs这些函数并不存在

**Comment by linhandev** [comment]
这些应该在一个util里，可以全局搜一下。我最近在等百度那边一个3d分割的库出第一个稳定版，之后会好好更新一下这个项目里的问题。

**Comment by Zyt-wenwne** [comment]
你好，谢谢，也期待您的更新，还有就是 f = open("./directions.csv")，这个csv是自己创建好的吗，还是生成的，我允许的时候报错了

**Comment by linhandev** [comment]
emm，那个是当时做lits的时候一些片子方向读出来有错误，当时手打的一个文件。如果你所有片子直接用nibabel读都是正的，所有有关这个direction的东西都可以略过去

**Comment by Zyt-wenwne** [comment]
好的，那我等大佬在更新吧，我也先看看，我之前用TF写过unet的3Dircadb_liver的分割，单独用dice的话训练收敛还好，但是val的曲线就不是很好，所以也希望向大佬学习

**Comment by linhandev** [comment]
可以看看百度那边的paddleseg，效果一般都很好

**Comment by Zyt-wenwne** [comment]
好的，谢谢，我在github上也看到一个https://github.com/MontaEllis/Pytorch-Medical-Segmentation是医学图像分割的代码，写了好多

**Comment by linhandev** [comment]
6的很，我有空也研究研究

**Comment by liushaoqian** [comment]
> 你好，这个eval的代码我确实有段时间没用了。但是就你说的这个问题，我看preds是有定义的。eval的脚本要指定yaml的配置文件，在配置文件中写测试分割结果和gt的位置，具体代码在[这](https://github.com/linhandev/medSeg/blob/edd433a8e86218d1759aabec8e5a9a7298b087d2/medseg/eval.py#L54)。 配置文件可以参考config中已有的



> 6的很，我有空也研究研究

python medseg/train.py -c config/lits.yaml --use_gpu --do_eval，您好，博主，我想问下lits.yaml这个文件具体指的什么文件啊，我没找到
